### ISSUE TITLE
Modded Minecraft support?

### ISSUE THREAD

**Issue by Kompreya** [Rolv-Apneseth/lib_game_detector#10]
I'm interested in adding support for common modded Minecraft launchers such as Prism, ATLauncher, and CurseForge.

Detecting the modpacks probably won't be difficult, since each launcher has a defined path where it stores modpacks including machine-readable metadata files for each modpack that includes info like the name, version, etc. 

My only concern, however, is typically modpacks don't include boxart.
Modpacks from both CurseForge and Modrinth include an icon, and can be pulled from each respective platform's api.
CurseForge lacks any sort of banner or boxart.
Modrinth allows modpack owners to upload a banner, which could potentially be used as the boxart, and pulled from the api.

Something I may personally help implement, and posting here for your thoughts or any ideas folks may have regarding boxart and implementation.

**Comment by Rolv-Apneseth** [comment]
I mean they could be added here - but without box art present locally on the system I wouldn't have them show in `rofi-games` (I don't want to do any network requests for fetching images). Also, do these launchers provide a way to launch straight into the modpacks? I think I've only used `gdlauncher` and that one specifically didn't.

I was thinking of potentially adding a config file or something where a user could define custom entries to `rofi-games` though. Maybe that could also have an option for matching games detected by this library that don't have a defined box art. You think that would be worthwhile?

**Comment by Kompreya** [comment]
Regarding network fetches, that's understandable. Perhaps a supplementary script for pulling them should they choose, otherwise end users would need to provide their own boxart (and perhaps place it in the respective modded mc instance path so rofi games sees it). 
I can look into writing something simple that can parse currently installed modpacks and pull icons/banners from CF/Modrinth and dump them to their respective instance paths. 

I primarily use prism and I know it has a way to launch the modpacks directly without needing to open Prism. I can get that info, I've certainly created my own .desktop files that execute the modpacks directly thru Prism.

Technically speaking any modpack can be launched without a launcher but that means setting up a script to pass parameters such as Java args, ram, and defining Java version. So it would definitely be up to the end user to do that for launchers that don't support launching packs directly.

I think custom defined entries would be very useful overall as an added feature. Let the user add an entry with custom exec parameters to their rofi-games script directly or perhaps add support for $PATH to custom made scripts that rofi-games can launch, and the scripts can point to boxart. 
I have a couple games configured in unusual ways that rofi-games can't detect, like a script for launching Runelite as to bypass the jagex launcher.

I'm a fan of your project, and definitely think it can use some more love, so I've been brainstorming some ideas and areas that could be improved from a UX perspective.

**Comment by Rolv-Apneseth** [comment]
> Regarding network fetches, that's understandable. Perhaps a supplementary script for pulling them should they choose, otherwise end users would need to provide their own boxart (and perhaps place it in the respective modded mc instance path so rofi games sees it).
> I can look into writing something simple that can parse currently installed modpacks and pull icons/banners from CF/Modrinth and dump them to their respective instance paths.

The paths wouldn't necessarily need to be next to the instance, or anywhere in particular since it would just be an absolute path to a readable file. You'd probably want them as part of your dotfiles alongside the `rofi-games` config even (at least I would).

But I hear you. Alternatively, the box art paths could be either local paths _or_ URLs, and then some supplementary script could be run to fetch those that are URLs for you. Sounds like that would need `rofi-games` to also ship a binary, which along with the URL change, could be a lot of extra work, and I'm not sure it's worth it. I could think about it though. What do you think?


> think custom defined entries would be very useful overall as an added feature. Let the user add an entry with custom exec parameters to their rofi-games script directly or perhaps add support for $PATH to custom made scripts that rofi-games can launch, and the scripts can point to boxart.

I'm not sure what you mean with that second part. I was thinking just simple entries of title, path to box art, path to game directory, and launch command, which are then just added to the list of parsed games from `lib_game_detector` at run time.

> I'm a fan of your project, and definitely think it can use some more love, so I've been brainstorming some ideas and areas that could be improved from a UX perspective.

Thanks, I appreciate that. Yeah, it's hard for me to imagine additional features when the launcher already covers all the games I really play so thanks.

**Comment by Rolv-Apneseth** [comment]
Hey @Kompreya, I've attempted to add in that config feature. It also allows defining box art for entries which are detected by this library, but don't have box art defined. Could you try it out, it's over on [this PR](https://github.com/Rolv-Apneseth/rofi-games/pull/21) for `rofi-games`?

**Comment by Kompreya** [comment]
Thank you! I gave it a test and it seems to work ok so far. 
![image](https://github.com/Rolv-Apneseth/lib_game_detector/assets/41587427/734028e6-6556-4091-9a8b-5791efd8b8d0)

I was able to use the config to:
- Change the box art for GW1 (steam version's default box art doesnt look as great)
- Add FFXIV (since it's a separate launcher entirely)
- Add a Prism modpack (I just used prism to create a .desktop shortcut, which provides the launch command)
- Add OSRS (like XIV, it also has a separate launcher)

**Comment by Rolv-Apneseth** [comment]
Nice, I'll merge that. That means that when there's support for modded minecraft launchers in this library, you'll be able to set just the box art and that should be enough for it to show up

**Comment by Rolv-Apneseth** [comment]
> Something I may personally help implement, and posting here for your thoughts or any ideas folks may have regarding boxart and implementation.

Did you want to do the detecting of Minecraft launchers by the way? If not, no worries. I won't get to it for a little while but can maybe start in a couple days

**Comment by Rolv-Apneseth** [comment]
What minecraft mod launchers do you think should be supported by the way? I pretty much have prism and AT done now, but I couldn't get `curseforge` or `multimc` to install, so I probably won't do those for now at least. Maybe the `feedthebeast` launcher too?

**Comment by Rolv-Apneseth** [comment]
One more thing @Kompreya, you think there should be some kind of prefix for the instance names? e.g. "Minecraft - Sky Factory"? I currently have just the instance name.

**Comment by Rolv-Apneseth** [comment]
Well, let me know if you have any more thoughts - closing for now
