### ISSUE TITLE
Error parsing a Steam library on Fedora

### ISSUE THREAD

**Issue by Rolv-Apneseth** [Rolv-Apneseth/lib_game_detector#5]
Error output provided in [this comment](https://github.com/Rolv-Apneseth/rofi-games/issues/7#issuecomment-1962776257) thanks to [@zDyanTB](https://github.com/zDyanTB)

```
ERROR lib_game_detector::linux::launchers::steam: 221: Error with parsing games from a Steam library.
Library: SteamLibrary { path_library: "/run/media/zdyant/HDII/SteamLibrary", path_steam_dir: "/home/zdyant/.local/share/Steam" }
Error:
                        Os { code: 2, kind: NotFound, message: "No such file or directory" }
 ```

**Comment by Rolv-Apneseth** [comment]
[@zDyanTB](https://github.com/zDyanTB) is the reported library path for your Steam library correct?

> /run/media/zdyant/HDII/SteamLibrary

**Comment by zDyanTB** [comment]
> [@zDyanTB](https://github.com/zDyanTB) is the reported library path for your Steam library correct?
> 
> > /run/media/zdyant/HDII/SteamLibrary

yes 
```console

zdyant/HDII/SteamLibrary 
❯ ls          
libraryfolder.vdf  steamapps

zdyant/HDII/SteamLibrary 
❯ pwd
/run/media/zdyant/HDII/SteamLibrary

```

**Comment by zDyanTB** [comment]
I did something. Idk, I rebooted the PC. Now it's working, but the theme.

```console
zdyant/HDII/SteamLibrary 
❯ rofi -modi games -show games -theme games-default
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rofi-mode-0.3.1/src/api.rs:182:64:
called `Result::unwrap()` on an `Err` value: InvalidSize
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    6592 IOT instruction (core dumped)  rofi -modi games -show games -theme games-default

zdyant/HDII/SteamLibrary took 7s 
❯ 

```
![image](https://github.com/Rolv-Apneseth/lib_game_detector/assets/102763838/dbd20621-bb93-47e2-907c-a60c14594c73)


I used my theme, now it's showing the arts.
![image](https://github.com/Rolv-Apneseth/lib_game_detector/assets/102763838/61eb56b5-d591-4478-a2fa-506c98382f3d)

But with my theme, sometimes, I can't close the launcher and I have to press `CTRL+C`, I've got the error.

```console
segmentation fault (core dumped) 
```

**Comment by zDyanTB** [comment]
Crash Note

```console
~/.config/rofi 
❯ rofi -modi games -show games -theme games-default
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rofi-mode-0.3.1/src/api.rs:182:64:
called `Result::unwrap()` on an `Err` value: InvalidSize
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    9152 IOT instruction (core dumped)  rofi -modi games -show games -theme games-default

~/.config/rofi took 7s 
```

**Comment by Rolv-Apneseth** [comment]
Very weird behaviour, I'll try tomorrow to see if I can figure it out. Thanks for reporting.

**Comment by Rolv-Apneseth** [comment]
Oh - could you also post your theme please, just so I can see if I get the same issues

**Comment by zDyanTB** [comment]
> Oh - could you also post your theme please, just so I can see if I get the same issues

Sure, [here](https://github.com/zDyanTB/HyprNova/blob/master/.config/rofi/themes/wallpaper-select.rasi) it is.

**Comment by Rolv-Apneseth** [comment]
Could you also give me that theme file at `~/.cache/wal/colors-rofi-dark.rasi`

**Comment by zDyanTB** [comment]
> Could you also give me that theme file at `~/.cache/wal/colors-rofi-dark.rasi`
> 
> Edit: nevermind, just using random colours and the theme seems fine
> 
> Edit2: seems like there is some issue but I don't think it's the theme's fault. Removing the `mainbox` part avoids the crash. I think it's related to not having the input box defined. Looking into it now.

The same error occur one time with your them as well

**Comment by Rolv-Apneseth** [comment]
> edit: Tough I think it was random

So you don't get it any more?

Anyway I believe I found out why the segmentation fault was occurring with your theme, so I created a PR to fix it in the base library this plugin uses, we'll need to wait to see what the author thinks. They'll probably know better than me.

As for the error with my theme, could you try installing again with the latest changes? I just made a small adjustment to the theme:

```bash
sudo just uninstall
git checkout main
git pull
sudo just install
```

**Comment by zDyanTB** [comment]
```console
rofi-games on  main is 󰏗 v1.6.6 via  v1.76.0 
❯ rofi -modi games -show games -theme games-default
ERROR lib_game_detector::linux::launchers::steam: 221: Error with parsing games from a Steam library.
Library: SteamLibrary { path_library: "/run/media/zdyant/HDII/SteamLibrary", path_steam_dir: "/home/zdyant/.local/share/Steam" }
Error:
                        Os { code: 2, kind: NotFound, message: "No such file or directory" }
ERROR rofi_games: 110: Unsupported input event: CustomInput { alt: false, selected: None }

rofi-games on  main is 󰏗 v1.6.6 via  v1.76.0 took 3s 
❯ 
 
```

The line
```console
ERROR rofi_games: 110: Unsupported input event: CustomInput { alt: false, selected: None }
```
Is the error I received when I hit enter

**Comment by Rolv-Apneseth** [comment]
I thought it might be the theme's icon sizes but I guess not. I'll wait and see if the creator of the library I'm using knows what might cause that issue.

**Comment by Rolv-Apneseth** [comment]
One last thing cause it might be helpful for them actually, could you run the command with `RUST_BACKTRACE=1` at the start and give the full output?

**Comment by zDyanTB** [comment]
> I thought it might be the theme's icon sizes but I guess not. I'll wait and see if the creator of the library I'm using knows what might cause that issue.

Using [this theme](https://github.com/zDyanTB/HyprNova/blob/master/.config/rofi/themes/nova-dark.rasi)
don't cause crashes

**Comment by Rolv-Apneseth** [comment]
Hmm. Maybe it's the percentage based element icon size on the other theme. Very confusing.

**Comment by zDyanTB** [comment]
Setting the element icon size to 30% makes the game art appear and makes no crashes.

But the launcher becomes laggy after the arts show up

https://github.com/Rolv-Apneseth/lib_game_detector/assets/102763838/f237c8c6-9720-47fb-b9fe-ef2842c5bd06

**Comment by Rolv-Apneseth** [comment]
How did you install `rofi`? Maybe it has some newer changes than the base `1.7.5` because I vaguely remember some of these issues like this when we were trying to get this to work with the newer version.

**Comment by zDyanTB** [comment]
I've used a [script](https://github.com/JaKooLit/Fedora-Hyprland?tab=readme-ov-file)<br>

I can try to reinstall, see if that works

**Comment by Rolv-Apneseth** [comment]
I see, it's installing `rofi-wayland`, which is the [lbonn fork](https://github.com/lbonn/rofi) (fedora package found [here](https://packages.fedoraproject.org/pkgs/rofi-wayland/rofi-wayland/)) but it was last updated 7 months ago. Seems to be at an awkward stage where it's not on the newer changes so we can't build it for the next version, but the previous version won't build correctly for it either. Not sure there's much that can be done unfortunately.

Could you try install that `rofi` fork directly from source, or try the plain `rofi` not built specifically for Wayland? Make sure to uninstall first, and do a fresh install of `rofi-games` too.

**Comment by zDyanTB** [comment]
Sure, I'll do it. 

Question: My videos are inverted to you?

**Comment by zDyanTB** [comment]
Everything looks fine. No crashes, no laggy, nothing.

But with my theme it gets laggy over time, Don't know why. Maybe the icon size matters?

I'm using the same rofi version as before

**Comment by zDyanTB** [comment]
I mean, when I switch to another game, using the arrows. It becomes slow to execute the command.

I'm talking [this theme](https://github.com/zDyanTB/HyprNova/blob/master/.config/rofi/themes/wallpaper-select.rasi)

I'll look for a way to update Rofi anyway

**Comment by Rolv-Apneseth** [comment]
Not ideal. If it still happens when `rofi` is updated (or you use the `rofi` package instead of the `rofi-wayland` one)  would you mind opening another issue over on `rofi-games`? I'll be closing this one for now.

Thanks a lot for reporting and giving feedback on the issue(s), I appreciate it.
